/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//
package thunb.gui;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import thunb.dao.UserDAO;

/**
 *
 * @author Banh Bao
 */
public class LoginJFrame extends javax.swing.JFrame {
    private Dimension sS = Toolkit.getDefaultToolkit().getScreenSize();
    private int xOffset = 0;
    private int yOffset = 0;
    /**
     * Creates new form MainJFrame
     */
    public LoginJFrame() {
        initComponents();
//        txtUsername.setText("");
//        txtPassword.setText("");
        this.setLocation(sS.width/2 - this.getSize().width/2 ,sS.height/2 - this.getSize().height/2 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntgActor = new javax.swing.ButtonGroup();
        jPanel_Login = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLCancel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPanelInfo = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel_Login.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_Login.setMaximumSize(new java.awt.Dimension(800, 550));
        jPanel_Login.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel_Login.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(805, 30));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_cancel_30px.png"))); // NOI18N
        jLCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCancelMouseClicked(evt);
            }
        });
        jPanel2.add(jLCancel, java.awt.BorderLayout.LINE_END);

        jPanel_Login.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(800, 520));
        jPanel4.setMinimumSize(new java.awt.Dimension(800, 520));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 520));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 557));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/loginbg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 50));

        JPanelInfo.setBackground(new java.awt.Color(255, 255, 204));
        JPanelInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPanelInfo.setForeground(new java.awt.Color(102, 0, 0));

        txtPassword.setText("123");

        txtUsername.setText("admin");

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/administrator_male_24px.png"))); // NOI18N
        jLabel3.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/password_24px.png"))); // NOI18N
        jLabel5.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(102, 0, 0));
        btnLogin.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelInfoLayout = new javax.swing.GroupLayout(JPanelInfo);
        JPanelInfo.setLayout(JPanelInfoLayout);
        JPanelInfoLayout.setHorizontalGroup(
            JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInfoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelInfoLayout.createSequentialGroup()
                        .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelInfoLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        JPanelInfoLayout.setVerticalGroup(
            JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInfoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addComponent(btnLogin)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.add(JPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 230));

        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("@THUNB");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 400, -1));

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel_Login.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_Login);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            //1 get data
            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());
            //validation data
            String valid = "";
            if (username.length() == 0) {
                valid += "Username can't be blank! \n";
            }
            if (password.length() == 0) {
                valid += "Password can't be blank! \n";
            }
            //2. Goi model
            if (valid.equals("")) {
                UserDAO dao = new UserDAO();
                String actor = dao.checkLogin(username, password);
                if (actor.equals("failed")) {
                    JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
                } else {
                    if (actor.equals("Director")) {
                        this.setVisible(false);
                        new AdminJFrame(username).setVisible(true);
                    } else if (actor.equals("Cast")) {
                        this.setVisible(false);
                        new UserJFrame(username).setVisible(true);
                    }else JOptionPane.showMessageDialog(this, "Your role is invalid");

                }

            } else {
                JOptionPane.showMessageDialog(this, valid);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jLCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLCancelMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xOffset = evt.getX();
        yOffset = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen()-xOffset, evt.getYOnScreen()-yOffset);
    }//GEN-LAST:event_jPanel2MouseDragged
    
    
    /**
     * @param args the command line arguments
     */
    //Show cac card
    private void showPanel(String panelName) {
        CardLayout layOut = (CardLayout) getContentPane().getLayout();
        layOut.show(getContentPane(), panelName);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelInfo;
    private javax.swing.ButtonGroup bntgActor;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Login;
    private javax.swing.JPasswordField txtPassword;
    private java.awt.TextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
