/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thunb.gui;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import thunb.dao.CastDAO;
import thunb.dao.UserDAO;
import thunb.dao.NotificationDAO;
import thunb.dao.RoleDAO;
import thunb.dao.ScheduleDAO;
import thunb.dto.CastDTO;
import thunb.dto.NotificationDTO;
import thunb.dto.ScheduleDTO;
import static thunb.dbutil.Util.*;
import thunb.dto.RoleDTO;

/**
 *
 * @author Banh Bao
 */
public class UserJFrame extends javax.swing.JFrame {

    private CastDTO cast = new CastDTO();
    private List<ScheduleDTO> scheduleList;
    private Dimension sS = Toolkit.getDefaultToolkit().getScreenSize();
    private int xOffset = 0;
    private int yOffset = 0;
    JFileChooser fileChooser = new JFileChooser();
    private DefaultTableModel tblModelNoti = null;
    private DefaultTableModel tblModelSchedule = null;
    private DefaultTableModel tblModelHistory = null;
    private DefaultTableModel tblModelRoleList = null;
    private String imgChoose;

    /**
     * Creates new form UserJFrame
     */
    public UserJFrame() {
        initComponents();
        this.setLocation(sS.width / 2 - this.getSize().width / 2, sS.height / 2 - this.getSize().height / 2);
    }

    public UserJFrame(String username) throws Exception {
        initComponents();
        inItRow(tblViewNoti);
        this.cast.setUsername(username);
        this.cast.setCastID(getCastID(username));
        this.scheduleList = getSchedule();
        this.setLocation(sS.width / 2 - this.getSize().width / 2, sS.height / 2 - this.getSize().height / 2);
        loadHomeInfo(username);
        tblModelNoti = (DefaultTableModel) tblViewNoti.getModel();
        tblModelSchedule = (DefaultTableModel) tblViewSchedule.getModel();
        tblModelHistory = (DefaultTableModel) tblViewHistory.getModel();
        tblModelRoleList = (DefaultTableModel) tblViewRole.getModel();
        inItRow(tblViewRole);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "GIF", "JPG", "JPEG", "PNG");
        fileChooser.setFileFilter(filter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_User = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jLCancel = new javax.swing.JLabel();
        jPanelCard = new javax.swing.JPanel();
        jPanelUserHome = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLUserName = new javax.swing.JLabel();
        jLLogOut = new javax.swing.JLabel();
        jPanelImageUser = new javax.swing.JPanel();
        jLUserImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        MNoti = new javax.swing.JPanel();
        jLTri = new javax.swing.JLabel();
        jLNotification = new javax.swing.JLabel();
        MSchedule = new javax.swing.JPanel();
        jLTri1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MRole = new javax.swing.JPanel();
        jLTri2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MHistory = new javax.swing.JPanel();
        jLTri3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel_Noti = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLBackAdminHome6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewNoti = new javax.swing.JTable();
        jPanel_Schedule = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLBackAdminHome3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblViewSchedule = new javax.swing.JTable();
        jPanel_Role = new javax.swing.JPanel();
        jLTiltleRolePanel = new javax.swing.JLabel();
        jLBackAdminHome4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewRole = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txtRoleDes = new javax.swing.JScrollPane();
        txtRoleDesForDownlooad = new javax.swing.JTextArea();
        txtRoleNameDes = new javax.swing.JLabel();
        downloadRoleDes = new javax.swing.JLabel();
        prbUpload = new javax.swing.JProgressBar();
        jPanel_History = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLBackAdminHome5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblViewHistory = new javax.swing.JTable();
        jPanel_Profile = new javax.swing.JPanel();
        jLBackAdminHome7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelImageUser1 = new javax.swing.JPanel();
        jLUserImageProfile = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLSaveProfile = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        txtProfileName = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        txtProfileEmail = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        txtProfilePassword = new javax.swing.JPasswordField();
        jPanel38 = new javax.swing.JPanel();
        txtProfilePhone = new javax.swing.JTextField();
        bntChangeImageProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_User.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_User.setPreferredSize(new java.awt.Dimension(800, 555));
        jPanel_User.setLayout(new java.awt.BorderLayout());

        bar.setBackground(new java.awt.Color(102, 0, 0));
        bar.setPreferredSize(new java.awt.Dimension(800, 30));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });
        bar.setLayout(new java.awt.BorderLayout());

        jLCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_cancel_30px.png"))); // NOI18N
        jLCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCancelMouseClicked(evt);
            }
        });
        bar.add(jLCancel, java.awt.BorderLayout.LINE_END);

        jPanel_User.add(bar, java.awt.BorderLayout.PAGE_START);

        jPanelCard.setBackground(new java.awt.Color(255, 255, 204));
        jPanelCard.setLayout(new java.awt.CardLayout());

        jPanelUserHome.setBackground(new java.awt.Color(255, 255, 204));
        jPanelUserHome.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 525));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/loginbg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelUserHome.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 525));

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGEMENT PROGRAM");

        jLUserName.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLUserName.setForeground(new java.awt.Color(102, 0, 0));
        jLUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/administrator_male_24px.png"))); // NOI18N

        jLLogOut.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        jLLogOut.setForeground(new java.awt.Color(102, 0, 0));
        jLLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogOut.setText("Log out");
        jLLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogOutMouseClicked(evt);
            }
        });

        jPanelImageUser.setBackground(new java.awt.Color(255, 255, 204));
        jPanelImageUser.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanelImageUser.add(jLUserImage);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        MNoti.setBackground(new java.awt.Color(255, 255, 204));
        MNoti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MNoti.setForeground(new java.awt.Color(255, 255, 204));
        MNoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNotiMouseClicked(evt);
            }
        });
        MNoti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTri.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLTri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_notification_100px.png"))); // NOI18N
        jLTri.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MNoti.add(jLTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        jLNotification.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLNotification.setForeground(new java.awt.Color(102, 0, 0));
        jLNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNotification.setText("NOTI: ");
        MNoti.add(jLNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        MSchedule.setBackground(new java.awt.Color(255, 255, 204));
        MSchedule.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MSchedule.setForeground(new java.awt.Color(255, 255, 204));
        MSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MScheduleMouseClicked(evt);
            }
        });
        MSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTri1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLTri1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_rules_100px.png"))); // NOI18N
        jLTri1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MSchedule.add(jLTri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SCHEDULE");
        MSchedule.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        MRole.setBackground(new java.awt.Color(255, 255, 204));
        MRole.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MRole.setForeground(new java.awt.Color(255, 255, 204));
        MRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MRoleMouseClicked(evt);
            }
        });
        MRole.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTri2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLTri2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_conference_100px.png"))); // NOI18N
        jLTri2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MRole.add(jLTri2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 90));

        jLabel7.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ROLE ");
        MRole.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        MHistory.setBackground(new java.awt.Color(255, 255, 204));
        MHistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MHistory.setForeground(new java.awt.Color(255, 255, 204));
        MHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MHistoryMouseClicked(evt);
            }
        });
        MHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTri3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLTri3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_clapperboard_100px.png"))); // NOI18N
        jLTri3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MHistory.add(jLTri3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        jLabel8.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HISTORY");
        MHistory.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MNoti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MNoti, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MRole, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("View Profile");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanelUserHome.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelCard.add(jPanelUserHome, "cardHome");

        jPanel_Noti.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOTIFICATION ");

        jLBackAdminHome6.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLBackAdminHome6.setForeground(new java.awt.Color(102, 0, 0));
        jLBackAdminHome6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_back_arrow_50px.png"))); // NOI18N
        jLBackAdminHome6.setText("Home");
        jLBackAdminHome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBackAdminHome6.setIconTextGap(0);
        jLBackAdminHome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackAdminHome6MouseClicked(evt);
            }
        });

        tblViewNoti.setBackground(new java.awt.Color(255, 255, 204));
        tblViewNoti.setForeground(new java.awt.Color(102, 0, 0));
        tblViewNoti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Time", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewNoti);

        javax.swing.GroupLayout jPanel_NotiLayout = new javax.swing.GroupLayout(jPanel_Noti);
        jPanel_Noti.setLayout(jPanel_NotiLayout);
        jPanel_NotiLayout.setHorizontalGroup(
            jPanel_NotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NotiLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(jPanel_NotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NotiLayout.createSequentialGroup()
                        .addComponent(jLBackAdminHome6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NotiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        jPanel_NotiLayout.setVerticalGroup(
            jPanel_NotiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NotiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLBackAdminHome6)
                .addContainerGap())
        );

        jPanelCard.add(jPanel_Noti, "cardNoti");

        jPanel_Schedule.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SCHEDULE");

        jLBackAdminHome3.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLBackAdminHome3.setForeground(new java.awt.Color(102, 0, 0));
        jLBackAdminHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_back_arrow_50px.png"))); // NOI18N
        jLBackAdminHome3.setText("Home");
        jLBackAdminHome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBackAdminHome3.setIconTextGap(0);
        jLBackAdminHome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackAdminHome3MouseClicked(evt);
            }
        });

        tblViewSchedule.setBackground(new java.awt.Color(255, 255, 204));
        tblViewSchedule.setForeground(new java.awt.Color(102, 0, 0));
        tblViewSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tribulation", "Role", "Locate", "StartDate", "EndDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblViewSchedule);

        javax.swing.GroupLayout jPanel_ScheduleLayout = new javax.swing.GroupLayout(jPanel_Schedule);
        jPanel_Schedule.setLayout(jPanel_ScheduleLayout);
        jPanel_ScheduleLayout.setHorizontalGroup(
            jPanel_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
            .addGroup(jPanel_ScheduleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ScheduleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLBackAdminHome3))
        );
        jPanel_ScheduleLayout.setVerticalGroup(
            jPanel_ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ScheduleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLBackAdminHome3))
        );

        jPanelCard.add(jPanel_Schedule, "cardSchedule");

        jPanel_Role.setBackground(new java.awt.Color(255, 255, 204));

        jLTiltleRolePanel.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLTiltleRolePanel.setForeground(new java.awt.Color(102, 0, 0));
        jLTiltleRolePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTiltleRolePanel.setText("LIST ROLE OF ");

        jLBackAdminHome4.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLBackAdminHome4.setForeground(new java.awt.Color(102, 0, 0));
        jLBackAdminHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_back_arrow_50px.png"))); // NOI18N
        jLBackAdminHome4.setText("Home");
        jLBackAdminHome4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBackAdminHome4.setIconTextGap(0);
        jLBackAdminHome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackAdminHome4MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Role infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(370, 321));

        tblViewRole.setBackground(new java.awt.Color(255, 255, 204));
        tblViewRole.setForeground(new java.awt.Color(102, 0, 0));
        tblViewRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Role "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblViewRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewRoleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblViewRole);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Role Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(340, 321));

        txtRoleDesForDownlooad.setBackground(new java.awt.Color(255, 255, 204));
        txtRoleDesForDownlooad.setColumns(20);
        txtRoleDesForDownlooad.setForeground(new java.awt.Color(102, 0, 0));
        txtRoleDesForDownlooad.setLineWrap(true);
        txtRoleDesForDownlooad.setRows(5);
        txtRoleDesForDownlooad.setWrapStyleWord(true);
        txtRoleDesForDownlooad.setBorder(null);
        txtRoleDesForDownlooad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRoleDes.setViewportView(txtRoleDesForDownlooad);

        txtRoleNameDes.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        txtRoleNameDes.setForeground(new java.awt.Color(102, 0, 0));
        txtRoleNameDes.setText("Role: ");

        downloadRoleDes.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        downloadRoleDes.setForeground(new java.awt.Color(102, 0, 0));
        downloadRoleDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downloadRoleDes.setText("DOWNLOAD");
        downloadRoleDes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        downloadRoleDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadRoleDesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRoleDes, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtRoleNameDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(downloadRoleDes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtRoleNameDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoleDes, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(downloadRoleDes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel_RoleLayout = new javax.swing.GroupLayout(jPanel_Role);
        jPanel_Role.setLayout(jPanel_RoleLayout);
        jPanel_RoleLayout.setHorizontalGroup(
            jPanel_RoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTiltleRolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RoleLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel_RoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBackAdminHome4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RoleLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RoleLayout.createSequentialGroup()
                        .addComponent(prbUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
        );
        jPanel_RoleLayout.setVerticalGroup(
            jPanel_RoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RoleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLTiltleRolePanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prbUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLBackAdminHome4))
        );

        jPanelCard.add(jPanel_Role, "cardRole");

        jPanel_History.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("HISTORY");

        jLBackAdminHome5.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLBackAdminHome5.setForeground(new java.awt.Color(102, 0, 0));
        jLBackAdminHome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_back_arrow_50px.png"))); // NOI18N
        jLBackAdminHome5.setText("Home");
        jLBackAdminHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBackAdminHome5.setIconTextGap(0);
        jLBackAdminHome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackAdminHome5MouseClicked(evt);
            }
        });

        tblViewHistory.setBackground(new java.awt.Color(255, 255, 204));
        tblViewHistory.setForeground(new java.awt.Color(102, 0, 0));
        tblViewHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tribulation", "Role", "Locate", "StartDate", "EndDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblViewHistory);

        javax.swing.GroupLayout jPanel_HistoryLayout = new javax.swing.GroupLayout(jPanel_History);
        jPanel_History.setLayout(jPanel_HistoryLayout);
        jPanel_HistoryLayout.setHorizontalGroup(
            jPanel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
            .addGroup(jPanel_HistoryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLBackAdminHome5))
            .addGroup(jPanel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_HistoryLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(167, Short.MAX_VALUE)))
        );
        jPanel_HistoryLayout.setVerticalGroup(
            jPanel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HistoryLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                .addComponent(jLBackAdminHome5))
            .addGroup(jPanel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_HistoryLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        jPanelCard.add(jPanel_History, "cardHistory");

        jPanel_Profile.setBackground(new java.awt.Color(255, 255, 204));

        jLBackAdminHome7.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLBackAdminHome7.setForeground(new java.awt.Color(102, 0, 0));
        jLBackAdminHome7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_back_arrow_50px.png"))); // NOI18N
        jLBackAdminHome7.setText("Home");
        jLBackAdminHome7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLBackAdminHome7.setIconTextGap(0);
        jLBackAdminHome7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackAdminHome7MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelImageUser1.setBackground(new java.awt.Color(255, 255, 204));
        jPanelImageUser1.setMaximumSize(new java.awt.Dimension(125, 125));
        jPanelImageUser1.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanelImageUser1.setPreferredSize(new java.awt.Dimension(125, 125));
        jPanelImageUser1.add(jLUserImageProfile);

        jLabel10.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PROFILE");

        jLSaveProfile.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLSaveProfile.setForeground(new java.awt.Color(102, 0, 0));
        jLSaveProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunb/images/icons8_save_50px.png"))); // NOI18N
        jLSaveProfile.setText("Save");
        jLSaveProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLSaveProfile.setIconTextGap(0);
        jLSaveProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSaveProfileMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 14), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 0));
        jLabel26.setText("Name:");

        jLabel27.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 0));
        jLabel27.setText("Phone:");

        jLabel30.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 0, 0));
        jLabel30.setText("Email:");

        jLabel31.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 0, 0));
        jLabel31.setText("Password:");

        jPanel43.setBackground(new java.awt.Color(255, 255, 204));
        jPanel43.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 0)));

        txtProfileName.setBackground(new java.awt.Color(255, 255, 204));
        txtProfileName.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtProfileName.setBorder(null);
        txtProfileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfileNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(txtProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel37.setBackground(new java.awt.Color(255, 255, 204));
        jPanel37.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 0)));

        txtProfileEmail.setBackground(new java.awt.Color(255, 255, 204));
        txtProfileEmail.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtProfileEmail.setBorder(null);
        txtProfileEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfileEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(txtProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel41.setBackground(new java.awt.Color(255, 255, 204));
        jPanel41.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 0)));

        txtProfilePassword.setBackground(new java.awt.Color(255, 255, 204));
        txtProfilePassword.setBorder(null);

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProfilePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(txtProfilePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel38.setBackground(new java.awt.Color(255, 255, 204));
        jPanel38.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 0, 0)));

        txtProfilePhone.setBackground(new java.awt.Color(255, 255, 204));
        txtProfilePhone.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtProfilePhone.setBorder(null);
        txtProfilePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfilePhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtProfilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel38Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(txtProfilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        bntChangeImageProfile.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        bntChangeImageProfile.setForeground(new java.awt.Color(102, 0, 0));
        bntChangeImageProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntChangeImageProfile.setText("Choose image");
        bntChangeImageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntChangeImageProfile.setIconTextGap(0);
        bntChangeImageProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntChangeImageProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLSaveProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bntChangeImageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelImageUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelImageUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntChangeImageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLSaveProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_ProfileLayout = new javax.swing.GroupLayout(jPanel_Profile);
        jPanel_Profile.setLayout(jPanel_ProfileLayout);
        jPanel_ProfileLayout.setHorizontalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLBackAdminHome7)
                .addContainerGap())
        );
        jPanel_ProfileLayout.setVerticalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBackAdminHome7)
                .addContainerGap())
        );

        jPanelCard.add(jPanel_Profile, "cardProfile");

        jPanel_User.add(jPanelCard, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private CastDTO getUserInfo(String username) throws Exception {
        CastDAO dao = new CastDAO();
        CastDTO dto = dao.getDTOByUsername(username);
        return dto;
    }

    private String getCastID(String username) throws Exception {
        CastDTO dto = getUserInfo(username);
        return dto.getCastID();
    }

    private List<ScheduleDTO> getSchedule() throws Exception {
        ScheduleDAO dao = new ScheduleDAO();
        List<ScheduleDTO> list = dao.getAllDTOByCastID(this.cast.getCastID());
        Collections.sort(list);
        return list;
    }

    private void inItRow(JTable table) {
        table.getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    private void loadHomeInfo(String username) throws Exception {
        this.cast = getUserInfo(username);
        jLUserName.setText(this.cast.getName());
        imgChoose = this.cast.getImage();

        ImageIcon imageIcon = new ImageIcon(imgChoose); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 
        imageIcon = new ImageIcon(newimg);  // transform it back
        jLUserImage.setIcon(imageIcon);

    }

    private void loadNoti() throws Exception {
        try {
            NotificationDAO dao = new NotificationDAO();
            List<NotificationDTO> list = dao.getNotiByCastID(cast.getCastID());
            showListNoti(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadSchedule() {
        try {
            tblModelSchedule.setRowCount(0);
            for (ScheduleDTO scheduleDTO : scheduleList) {
                if (!checkDateHistory(scheduleDTO.getEndDate())) {
                    tblModelSchedule.addRow(scheduleDTO.toVector());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadHistory() {
        try {
            tblModelHistory.setRowCount(0);
            for (ScheduleDTO scheduleDTO : scheduleList) {
                if (checkDateHistory(scheduleDTO.getEndDate())) {
                    tblModelHistory.addRow(scheduleDTO.toVector());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadRoleList() {
        try {
            RoleDAO dao = new RoleDAO();
            List<RoleDTO> list = dao.getDTOByCastID(this.cast.getCastID());
            showListRole(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showListRole(List<RoleDTO> list) {
        try {
            tblModelRoleList.setRowCount(0);
            for (RoleDTO roleDTO : list) {
                tblModelRoleList.addRow(roleDTO.toVector());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showListNoti(List<NotificationDTO> list) {
        try {
            tblModelNoti.setRowCount(0);
            for (NotificationDTO notificationDTO : list) {
                tblModelNoti.addRow(notificationDTO.toVector());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    private void jLCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLCancelMouseClicked

    private void barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_barMouseClicked

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        // TODO add your handling code here:
        xOffset = evt.getX();
        yOffset = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - xOffset, evt.getYOnScreen() - yOffset);
    }//GEN-LAST:event_barMouseDragged

    private void jLLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogOutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_jLLogOutMouseClicked

    private void MNotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNotiMouseClicked
        // TODO add your handling code here:
        showPanel("cardNoti");
        tblViewNoti.getColumnModel().getColumn(1).setMinWidth(160);
        tblViewNoti.getColumnModel().getColumn(1).setMaxWidth(160);
        tblViewNoti.getColumnModel().getColumn(1).setPreferredWidth(160);

        try {
            loadNoti();
        } catch (Exception ex) {
            Logger.getLogger(UserJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MNotiMouseClicked

    private void MScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MScheduleMouseClicked
        // TODO add your handling code here:
        showPanel("cardSchedule");
        loadSchedule();
        tblViewSchedule.getColumnModel().getColumn(3).setMinWidth(80);
        tblViewSchedule.getColumnModel().getColumn(3).setMaxWidth(80);
        tblViewSchedule.getColumnModel().getColumn(3).setPreferredWidth(80);

        tblViewSchedule.getColumnModel().getColumn(4).setMinWidth(80);
        tblViewSchedule.getColumnModel().getColumn(4).setMaxWidth(80);
        tblViewSchedule.getColumnModel().getColumn(4).setPreferredWidth(80);
    }//GEN-LAST:event_MScheduleMouseClicked

    private void MRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MRoleMouseClicked
        // TODO add your handling code here:
        showPanel("cardRole");
        jLTiltleRolePanel.setText("LIST ROLE OF CAST: " + this.cast.getName());
        loadRoleList();
        //loadListRole();
    }//GEN-LAST:event_MRoleMouseClicked

    private void MHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MHistoryMouseClicked
        // TODO add your handling code here:
        showPanel("cardHistory");
        loadHistory();
        tblViewHistory.getColumnModel().getColumn(3).setMinWidth(80);
        tblViewHistory.getColumnModel().getColumn(3).setMaxWidth(80);
        tblViewHistory.getColumnModel().getColumn(3).setPreferredWidth(80);

        tblViewHistory.getColumnModel().getColumn(4).setMinWidth(80);
        tblViewHistory.getColumnModel().getColumn(4).setMaxWidth(80);
        tblViewHistory.getColumnModel().getColumn(4).setPreferredWidth(80);
    }//GEN-LAST:event_MHistoryMouseClicked

    private void jLBackAdminHome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackAdminHome3MouseClicked
        // TODO add your handling code here:
        showPanel("cardHome");
    }//GEN-LAST:event_jLBackAdminHome3MouseClicked

    private void jLBackAdminHome4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackAdminHome4MouseClicked
        // TODO add your handling code here:
        showPanel("cardHome");
    }//GEN-LAST:event_jLBackAdminHome4MouseClicked

    private void jLBackAdminHome5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackAdminHome5MouseClicked
        // TODO add your handling code here:
        showPanel("cardHome");
    }//GEN-LAST:event_jLBackAdminHome5MouseClicked

    private void jLBackAdminHome6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackAdminHome6MouseClicked
        // TODO add your handling code here:
        showPanel("cardHome");
    }//GEN-LAST:event_jLBackAdminHome6MouseClicked

    private void jLBackAdminHome7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackAdminHome7MouseClicked
        // TODO add your handling code here:
        showPanel("cardHome");
        ImageIcon imageIcon = new ImageIcon(imgChoose); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 
        imageIcon = new ImageIcon(newimg);  // transform it back
        jLUserImage.setIcon(imageIcon);
    }//GEN-LAST:event_jLBackAdminHome7MouseClicked

    private void txtProfileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfileNameActionPerformed

    private void txtProfileEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfileEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfileEmailActionPerformed

    private void txtProfilePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfilePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfilePhoneActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        showPanel("cardProfile");
        try {
            CastDTO dto = getUserInfo(cast.getUsername());

            //UserDAO dao = new UserDAO();
            txtProfileName.setText(dto.getName());
            txtProfilePhone.setText(dto.getPhone());
            txtProfileEmail.setText(dto.getEmail());

            ImageIcon imageIcon = new ImageIcon(imgChoose); // load the image to a imageIcon
            Image image = imageIcon.getImage(); // transform it
            Image newimg = image.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 
            imageIcon = new ImageIcon(newimg);  // transform it back
            jLUserImageProfile.setIcon(imageIcon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLSaveProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSaveProfileMouseClicked
        // TODO add your handling code here:
        String name, image, phone, email, pass;
        String valid = "";
        CastDAO daoC = new CastDAO();
        UserDAO daoU = new UserDAO();
        name = txtProfileName.getText();;
        image = imgChoose;
        phone = txtProfilePhone.getText();
        email = txtProfileEmail.getText();
        pass = new String(txtProfilePassword.getPassword());
        if (name.equals("")) {
            valid += "Name can not empty \n";
        }
        if (phone.equals("")) {
            valid += "Phone can not empty \n";
        }
        if (email.equals("")) {
            valid += "Email can not empty \n";
        }
        if (pass.equals("")) {
            valid += "Password can not empty \n";
        }
        if (valid.equals("")) {
            try {
                if (daoU.update(cast.getUsername(), pass)
                        && daoC.updateProfile(cast.getUsername(), name, image, phone, email)) {
                    JOptionPane.showMessageDialog(this, "Update successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Update Failed!");
                }
            } catch (Exception ex) {
                Logger.getLogger(UserJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, valid);
        }

    }//GEN-LAST:event_jLSaveProfileMouseClicked

    private void tblViewRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewRoleMouseClicked
        // TODO add your handling code here:
        int row = tblViewRole.getSelectedRow();
        if (row == -1) {
            return;
        }
        String roleID = (String) tblModelRoleList.getValueAt(row, 0);
        RoleDAO dao = new RoleDAO();
        RoleDTO dto = null;
        try {
            dto = dao.getDTOByRoleID(roleID);
        } catch (Exception ex) {
            Logger.getLogger(UserJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (dto != null) {
            txtRoleNameDes.setText("Role: " + dto.getRoleName());
            String description = dao.loadRoleDesFromFile(dto.getRoleDes());
            txtRoleDesForDownlooad.setText(description);
        }
    }//GEN-LAST:event_tblViewRoleMouseClicked

    private void downloadRoleDesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadRoleDesMouseClicked
        // TODO add your handling code here:
        int row = tblViewRole.getSelectedRow();
        if (row == -1) {
            return;
        }
        String roleID = (String) tblModelRoleList.getValueAt(row, 0);
        RoleDAO dao = new RoleDAO();
        RoleDTO dto = null;
        try {
            dto = dao.getDTOByRoleID(roleID);
        } catch (Exception ex) {
            Logger.getLogger(UserJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (dto != null) {
            try {

                fileChooser = new JFileChooser();
                fileChooser.setMultiSelectionEnabled(false);
                fileChooser.setDialogTitle("Choose folder");
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                //fileChooser.setAcceptAllFileFilterUsed(false);
                int result = fileChooser.showSaveDialog(this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    File f = fileChooser.getSelectedFile();

                    if (f.isFile()) {
                        JOptionPane.showMessageDialog(this, "Please choose place to save!");
                    } else {
                        String inputPath = dto.getRoleDes();
                        String downloadPath = f.getPath() + "/" + dto.getRoleName() + ".txt";

                        if (dao.cpyFile(inputPath, downloadPath, prbUpload)) {

                        } else {
                            JOptionPane.showMessageDialog(this, "Download failed!");
                        }
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_downloadRoleDesMouseClicked

    private void bntChangeImageProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChangeImageProfileMouseClicked
        // TODO add your handling code here:
        try {
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File f = fileChooser.getSelectedFile();

                if (f.isFile()) {
                    copyFile(f.getPath(), "src/thunb/images/cast_image/" + f.getName());
                    imgChoose = "src/thunb/images/cast_image/" + f.getName();
                    ImageIcon imageIcon = new ImageIcon("src/thunb/images/cast_image/" + f.getName()); // load the image to a imageIcon
                    Image image = imageIcon.getImage(); // transform it
                    Image newimg = image.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way 
                    imageIcon = new ImageIcon(newimg);  // transform it back
                    jLUserImageProfile.setIcon(imageIcon);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_bntChangeImageProfileMouseClicked

    private void showPanel(String panelName) {
        CardLayout layOut = (CardLayout) jPanelCard.getLayout();
        layOut.show(jPanelCard, panelName);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MHistory;
    private javax.swing.JPanel MNoti;
    private javax.swing.JPanel MRole;
    private javax.swing.JPanel MSchedule;
    private javax.swing.JPanel bar;
    private javax.swing.JLabel bntChangeImageProfile;
    private javax.swing.JLabel downloadRoleDes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBackAdminHome3;
    private javax.swing.JLabel jLBackAdminHome4;
    private javax.swing.JLabel jLBackAdminHome5;
    private javax.swing.JLabel jLBackAdminHome6;
    private javax.swing.JLabel jLBackAdminHome7;
    private javax.swing.JLabel jLCancel;
    private javax.swing.JLabel jLLogOut;
    private javax.swing.JLabel jLNotification;
    private javax.swing.JLabel jLSaveProfile;
    private javax.swing.JLabel jLTiltleRolePanel;
    private javax.swing.JLabel jLTri;
    private javax.swing.JLabel jLTri1;
    private javax.swing.JLabel jLTri2;
    private javax.swing.JLabel jLTri3;
    private javax.swing.JLabel jLUserImage;
    private javax.swing.JLabel jLUserImageProfile;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel jPanelImageUser;
    private javax.swing.JPanel jPanelImageUser1;
    private javax.swing.JPanel jPanelUserHome;
    private javax.swing.JPanel jPanel_History;
    private javax.swing.JPanel jPanel_Noti;
    private javax.swing.JPanel jPanel_Profile;
    private javax.swing.JPanel jPanel_Role;
    private javax.swing.JPanel jPanel_Schedule;
    private javax.swing.JPanel jPanel_User;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JProgressBar prbUpload;
    private javax.swing.JTable tblViewHistory;
    private javax.swing.JTable tblViewNoti;
    private javax.swing.JTable tblViewRole;
    private javax.swing.JTable tblViewSchedule;
    private javax.swing.JTextField txtProfileEmail;
    private javax.swing.JTextField txtProfileName;
    private javax.swing.JPasswordField txtProfilePassword;
    private javax.swing.JTextField txtProfilePhone;
    private javax.swing.JScrollPane txtRoleDes;
    private javax.swing.JTextArea txtRoleDesForDownlooad;
    private javax.swing.JLabel txtRoleNameDes;
    // End of variables declaration//GEN-END:variables
}
